# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tpc.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ttpc.proto\x12\x03rpc\"d\n\tLeaderMsg\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.rpc.MessageType\x12\x1b\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x0b.rpc.Action\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"\'\n\x08Response\x12\x1b\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0b.rpc.Action*5\n\x06\x41\x63tion\x12\x0b\n\x07PREPARE\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01\x12\n\n\x06\x43OMMIT\x10\x02\x12\x07\n\x03\x41\x43K\x10\x03*#\n\x0bMessageType\x12\x08\n\x04VOTE\x10\x00\x12\n\n\x06GLOBAL\x10\x01\x32=\n\x0eTwoPhaseCommit\x12+\n\x06TPCMsg\x12\x0e.rpc.LeaderMsg\x1a\r.rpc.Response(\x01\x30\x01\x62\x06proto3')
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='rpc.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREPARE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABORT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=161,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='rpc.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOTE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GLOBAL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=216,
  serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
PREPARE = 0
ABORT = 1
COMMIT = 2
ACK = 3
VOTE = 0
GLOBAL = 1



_LEADERMSG = _descriptor.Descriptor(
  name='LeaderMsg',
  full_name='rpc.LeaderMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rpc.LeaderMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='rpc.LeaderMsg.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc.LeaderMsg.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc.LeaderMsg.value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=118,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='rpc.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='rpc.Response.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=159,
)

_LEADERMSG.fields_by_name['type'].enum_type = _MESSAGETYPE
_LEADERMSG.fields_by_name['action'].enum_type = _ACTION
_RESPONSE.fields_by_name['action'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['LeaderMsg'] = _LEADERMSG
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LeaderMsg = _reflection.GeneratedProtocolMessageType('LeaderMsg', (_message.Message,), {
  'DESCRIPTOR' : _LEADERMSG,
  '__module__' : 'tpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.LeaderMsg)
  })
_sym_db.RegisterMessage(LeaderMsg)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'tpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Response)
  })
_sym_db.RegisterMessage(Response)



_TWOPHASECOMMIT = _descriptor.ServiceDescriptor(
  name='TwoPhaseCommit',
  full_name='rpc.TwoPhaseCommit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=253,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='TPCMsg',
    full_name='rpc.TwoPhaseCommit.TPCMsg',
    index=0,
    containing_service=None,
    input_type=_LEADERMSG,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWOPHASECOMMIT)

DESCRIPTOR.services_by_name['TwoPhaseCommit'] = _TWOPHASECOMMIT

# @@protoc_insertion_point(module_scope)
